// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktknzhypndszujoakaxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0a256aHlwbmRzenVqb2FrYXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTA0NDcsImV4cCI6MjA3MjM4NjQ0N30.5mi6f8szwCW9aUwheetf7x4R4Sbdj1AaZ9gqD0r4vKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});